# Generated by Django 3.2 on 2021-05-31 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Additional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_name', models.CharField(max_length=150, verbose_name='Наименование услуги')),
                ('content', models.TextField(blank=True, verbose_name='Описание услуги')),
                ('price', models.IntegerField(verbose_name='Стоимость')),
                ('duration', models.CharField(blank=True, max_length=100, verbose_name='продолжительность')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления услуги')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'Дополнительная услуга',
                'verbose_name_plural': 'Дополнительные услуги',
                'ordering': [],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=150, verbose_name='Тип услуги')),
                ('content', models.TextField(blank=True, verbose_name='Описание услуги')),
                ('price', models.IntegerField(verbose_name='Стоимость')),
                ('duration', models.CharField(blank=True, max_length=100, verbose_name='продолжительность')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления услуги')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('amount', models.IntegerField(blank=True, default=0)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Cleaning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_name', models.CharField(max_length=150, verbose_name='Номер этапа')),
                ('content', models.TextField(blank=True, verbose_name='Описание процедуры')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('photo', models.ImageField(blank=True, upload_to='photo/%Y/%m/%d', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Этап очистки',
                'verbose_name_plural': 'Этапы очистки',
                'ordering': [],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=150, verbose_name='Фамилия')),
                ('telephone_number', models.CharField(max_length=150, verbose_name='Номер телефона клиента')),
                ('activity', models.CharField(blank=True, max_length=150, verbose_name='Род деятельности')),
                ('birthday', models.DateField(blank=True, default='10.12.2000', verbose_name='День рождения')),
                ('number_of_visits', models.IntegerField(default=0)),
                ('photo', models.ImageField(blank=True, upload_to='photo/clients/%Y/%m/%d', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': [],
            },
        ),
        migrations.CreateModel(
            name='VisitAsk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone_number', models.CharField(max_length=100, verbose_name='Номер телефона')),
                ('client_name', models.CharField(blank=True, max_length=100, verbose_name='Как Вас зовут')),
                ('comment', models.TextField(default='123', verbose_name='Комментарий')),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата визита')),
                ('price', models.IntegerField(blank=True, default='250', verbose_name='Стоимость')),
                ('duration', models.DurationField(blank=True, default='03:00:00', help_text='часы:минуты:секунды', verbose_name='Длительность процедуры')),
                ('content', models.TextField(blank=True, verbose_name='Описание процедуры')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('photo_before', models.ImageField(blank=True, upload_to='photo/visits/before/%Y/%m/%d', verbose_name='Фото до')),
                ('photo_after', models.ImageField(blank=True, upload_to='photo/visits/after/%Y/%m/%d', verbose_name='Фото после')),
                ('telephone_number', models.CharField(blank=True, max_length=100, verbose_name='Номер телефона')),
                ('client_name', models.CharField(max_length=100, verbose_name='Как Вас зовут')),
                ('additional', models.ManyToManyField(blank=True, to='services.Additional', verbose_name='Доп. услуги')),
                ('category', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='services.category', verbose_name='Услуга')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Визит',
                'verbose_name_plural': 'Визиты',
                'ordering': ['-work_date'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Noone', max_length=150)),
                ('email', models.EmailField(default='email@gmail.com', max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('content', models.TextField(verbose_name='Содерджание комментария')),
                ('is_published', models.BooleanField(default=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.visit', verbose_name='Комментарий')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
