# Generated by Django 3.2 on 2021-05-31 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='client_name',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='telephone_number',
        ),
    ]
