# Generated by Django 3.2 on 2021-06-02 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20210531_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitask',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.category', verbose_name='Тип маникюра'),
        ),
    ]
