# Generated by Django 3.2 on 2021-06-02 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_visitask_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitask',
            name='category',
        ),
        migrations.AddField(
            model_name='visitask',
            name='additional',
            field=models.ManyToManyField(to='services.Additional', verbose_name='Доп услуги'),
        ),
    ]
