# Generated by Django 3.2 on 2021-06-09 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_auto_20210602_1632'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cleaning',
            options={'ordering': [], 'verbose_name': 'Этап очистки', 'verbose_name_plural': 'Страница "Стерилизация"'},
        ),
        migrations.AddField(
            model_name='visitask',
            name='visit_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата визита'),
        ),
    ]
