# Generated by Django 3.2 on 2021-06-09 14:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_auto_20210609_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitask',
            name='visit_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата визита'),
        ),
    ]
